### ISSUE TITLE
Add Compatibility to Track Styling with Multiple Browsers

### ISSUE THREAD

**Issue by javitrejo14** [cs481-ekh/f22-viz-kids#113]

**Comment by vpzomtrrfrt** [comment]
wasn't this already done in #107?

**Comment by javitrejo14** [comment]
Spent about 4 hours or more split between multiple days setting up a VM on this loaner laptop from the CS department. Had to go back and forth with department IT to get the right permissions

**Comment by javitrejo14** [comment]
Spent about 3 hours researching how browsers react to different style sheet components, and then adding the compatibility of track to Firefox. Also tested the other browsers
