### ISSUE TITLE
Toggle looped playback controls

### ISSUE THREAD

**Issue by PTLux1517** [cs481-ekh/f22-viz-kids#128]
As a user, I want to be able to toggle between looped and non-looped playback, so that I can either crop to a specific gait cycle and loop it, or play through a full trial only once per click of the play button.

## Definition of Done
- [x] Playback mode can be toggled between looped and non-looped via a labeled checkbox below the play button
- [x] Main menu button, under controls help, has instructions for toggling looped playback

## Tasks
- [x] #144
- [x] #145

**Comment by ConnorJacksonBSU** [comment]
This user story is done, pending one small change in pull request. I do not think it is necessary to put anything about the loop checkbox into the menu, it is straightforward
